# Basic
hard_tabs            = false
max_width = 120
# comment_width = 100
tab_spaces    = 4
# wrap_comments = true
use_small_heuristics = "Max"
# Imports
imports_granularity = "Crate"
reorder_imports     = true
group_imports       = "StdExternalCrate"

# Consistency
newline_style = "Unix"
# Misc
chain_width                = 80
# spaces_around_ranges       = false
# binop_separator            = "Back"
# reorder_impl_items         = false
match_arm_leading_pipes    = "Preserve"
# match_arm_blocks           = false
match_block_trailing_comma = false
# trailing_comma             = "Vertical"
# trailing_semicolon         = false
use_field_init_shorthand   = true
# ignore                     = ["bridges"]
edition                    = "2021"